/* Automatically generated by configure - do not modify! */
#define VERSION "1.1a"
#define PACKAGE "ushare"
#define PACKAGE_NAME "uShare"
#define SYSCONFDIR "/Users/dkirker/projects/webOS/Muses/libs//etc"
#define LOCALEDIR "/Users/dkirker/projects/webOS/Muses/libs//share/locale"
#define CONFIG_NLS 1
